/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sisoperativos2costatucci.gui;

import com.mycompany.sisoperativos2costatucci.logic.Block;
import com.mycompany.sisoperativos2costatucci.logic.Directory;
import com.mycompany.sisoperativos2costatucci.logic.File;
import com.mycompany.sisoperativos2costatucci.logic.GestorDisco;
import com.mycompany.sisoperativos2costatucci.logic.Queue;
import com.mycompany.sisoperativos2costatucci.logic.Recovery;
import com.mycompany.sisoperativos2costatucci.logic.Request;
import com.mycompany.sisoperativos2costatucci.logic.Row;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import java.awt.Color;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.nio.file.Files;
import java.nio.file.Paths;
import org.json.JSONArray;
import org.json.JSONObject;
import org.json.JSONException;
import java.util.Iterator;

/**
 *
 * @author gabri
 */
public class JFramePrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFramePrincipal.class.getName());
    private GestorDisco miDisco;
    private Queue generalRequests;
    private int header;
    private String mode;
    private Queue log;

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents();
        miDisco = new GestorDisco(181, 50);
        header = 0;
        generalRequests = new Queue("Requests");
        log = new Queue("log");
        log.addRow(new Row(null,null,true));
        mode = null;
        panelContenedorDisco.setLayout(new java.awt.BorderLayout());
        panelContenedorDisco.removeAll();
        panelContenedorDisco.add(miDisco.getVistaDisco(), java.awt.BorderLayout.CENTER);
        panelContenedorDisco.revalidate();
        panelContenedorDisco.repaint();
        iniciarDatosDePrueba();
    }

// ==========================================
// 1. GENERADOR DE COLORES ALEATORIOS
// ==========================================
private Color obtenerColorAleatorio() {
    // Generamos valores entre 0.2 y 0.8 
    // Esto evita el negro total (0.0) y el blanco total (1.0)
    float r = 0.2f + (float) Math.random() * 0.6f;
    float g = 0.2f + (float) Math.random() * 0.6f;
    float b = 0.2f + (float) Math.random() * 0.6f;

    // Retornamos el color. .brighter() ayuda a que resalten en el gris del disco.
    return new Color(r, g, b).brighter();
}

// ==========================================
// 2. MÉTODO RECURSIVO PARA PINTAR EL DISCO
// ==========================================
    private void pintarArchivosEnDisco(Directory carpetaLogica, PanelSD panelDisco) {
        if (carpetaLogica.getFiles() != null) {
            File actualArchivo = carpetaLogica.getFiles().getFirstFile();
            while (actualArchivo != null) {
                Color colorArchivo = obtenerColorAleatorio();
                Block actualBloque = actualArchivo.getFirstBlock();
                while (actualBloque != null) {
                    panelDisco.asignarBloqueVisual(actualBloque.getId(), colorArchivo);
                    actualBloque = actualBloque.getNext();
                }
                actualArchivo = actualArchivo.getNext();
            }
        }
        if (carpetaLogica.getDirectories() != null) {
            Directory actualDir = carpetaLogica.getDirectories().getFirstDirectory();
            while (actualDir != null) {
                pintarArchivosEnDisco(actualDir, panelDisco);
                actualDir = actualDir.getNext();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        PanelControles = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jusuario = new javax.swing.JRadioButton();
        jadminisrtador1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboPlan = new javax.swing.JComboBox<>();
        crear = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        eliminar1 = new javax.swing.JButton();
        crear1 = new javax.swing.JButton();
        update = new javax.swing.JButton();
        Json = new javax.swing.JButton();
        paneArbol = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbolDirectorios = new javax.swing.JTree();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        panelContenedorDisco = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setToolTipText("");

        PanelControles.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("Controles");
        jLabel1.setOpaque(true);

        buttonGroup1.add(jusuario);
        jusuario.setText("Usuario");
        jusuario.addActionListener(this::jusuarioActionPerformed);

        buttonGroup1.add(jadminisrtador1);
        jadminisrtador1.setText("Administrador");
        jadminisrtador1.addActionListener(this::jadminisrtador1ActionPerformed);

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Modo:");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Planificador:");
        jLabel3.setOpaque(true);

        jComboPlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIFO", "SSTF", "SCAN", "C-SCAN" }));
        jComboPlan.addActionListener(this::jComboPlanActionPerformed);

        crear.setText("Crear Archivo");
        crear.addActionListener(this::crearActionPerformed);

        eliminar.setText("Eliminar");
        eliminar.addActionListener(this::eliminarActionPerformed);

        eliminar1.setText("Leer");
        eliminar1.addActionListener(this::eliminar1ActionPerformed);

        crear1.setText("Crear Directorio");
        crear1.addActionListener(this::crear1ActionPerformed);

        update.setText("Update");
        update.addActionListener(this::updateActionPerformed);

        Json.setText("Cargar JSON");
        Json.addActionListener(this::JsonActionPerformed);

        javax.swing.GroupLayout PanelControlesLayout = new javax.swing.GroupLayout(PanelControles);
        PanelControles.setLayout(PanelControlesLayout);
        PanelControlesLayout.setHorizontalGroup(
            PanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlesLayout.createSequentialGroup()
                .addGroup(PanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelControlesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(PanelControlesLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(PanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jusuario)
                            .addGroup(PanelControlesLayout.createSequentialGroup()
                                .addGroup(PanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jadminisrtador1))
                                .addGap(63, 63, 63)
                                .addGroup(PanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(PanelControlesLayout.createSequentialGroup()
                                        .addComponent(jComboPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(crear)
                                        .addGap(15, 15, 15)
                                        .addComponent(crear1)
                                        .addGap(18, 18, 18)
                                        .addComponent(eliminar)
                                        .addGap(18, 18, 18)
                                        .addComponent(eliminar1)
                                        .addGap(18, 18, 18)
                                        .addComponent(update)
                                        .addGap(18, 18, 18)
                                        .addComponent(Json)))))))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        PanelControlesLayout.setVerticalGroup(
            PanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jadminisrtador1)
                    .addComponent(jComboPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crear)
                    .addComponent(eliminar)
                    .addComponent(eliminar1)
                    .addComponent(crear1)
                    .addComponent(update)
                    .addComponent(Json))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jusuario)
                .addGap(42, 42, 42))
        );

        paneArbol.setBackground(new java.awt.Color(51, 102, 255));

        jScrollPane1.setViewportView(arbolDirectorios);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sistema de Archivos");
        jLabel4.setOpaque(true);

        javax.swing.GroupLayout paneArbolLayout = new javax.swing.GroupLayout(paneArbol);
        paneArbol.setLayout(paneArbolLayout);
        paneArbolLayout.setHorizontalGroup(
            paneArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneArbolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(paneArbolLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 321, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paneArbolLayout.setVerticalGroup(
            paneArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneArbolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cola de Procesos");
        jLabel5.setOpaque(true);

        jScrollPane2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jScrollPane2ComponentShown(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Log de eventos");
        jLabel6.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        jTabbedPane2.setBackground(new java.awt.Color(255, 51, 102));

        panelContenedorDisco.setLayout(new java.awt.BorderLayout());
        jTabbedPane2.addTab("tab1", panelContenedorDisco);

        jTabbedPane1.setOpaque(true);
        jTabbedPane2.addTab("tab2", jTabbedPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelControles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(paneArbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2)
                .addGap(18, 18, 18))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PanelControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jusuarioActionPerformed
        if (mode == "admin" || mode == null){
            mode = "user";
            System.out.println("cambio de modo");
        }
    }//GEN-LAST:event_jusuarioActionPerformed

    private void jadminisrtador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadminisrtador1ActionPerformed
        if (mode == "user"|| mode == null){
            mode = "admin";
            System.out.println("cambio de modo");            
        }
    }//GEN-LAST:event_jadminisrtador1ActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        if (!jadminisrtador1.isSelected()) {
        JOptionPane.showMessageDialog(this, 
            "Acceso denegado. Use el modo Administrador.", 
            "Error de Permisos", 
            JOptionPane.ERROR_MESSAGE);
        return; 
    }
    DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) arbolDirectorios.getLastSelectedPathComponent();
    if (nodoSeleccionado == null || !(nodoSeleccionado.getUserObject() instanceof Directory)) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione una CARPETA en el árbol para crear el archivo.");
        return;
    }
    Directory dirPadre = (Directory) nodoSeleccionado.getUserObject();
    String nombre = JOptionPane.showInputDialog(this, "Nombre del nuevo archivo:");
    if (nombre == null || nombre.trim().isEmpty()) return;
    String bloquesStr = JOptionPane.showInputDialog(this, "Cantidad de bloques a ocupar:");
    if (bloquesStr == null) return;
    try {
        int tamano = Integer.parseInt(bloquesStr);
        
        // 1. Creamos el objeto (esto no toca el disco visual aún)
        File nuevoFile = miDisco.crearArchivo(tamano, "Admin", obtenerColorAleatorio());
        
        // 2. Intentamos la operación "segura" que dispara la recuperación si falla
        Recovery resultado = miDisco.ejecutarOperacionSegura(nuevoFile, "CREAR");
        
        if (!resultado.success) {
            JOptionPane.showMessageDialog(this, 
                "¡FALLA DETECTADA!\n" +
                "El sistema ha ejecutado una recuperación semiautomática.\n" +
                "Estado: " + resultado.errorMessage + "\n" +
                "Bloques restaurados: " + resultado.processedCount,
                "Recuperación del Sistema", 
                JOptionPane.WARNING_MESSAGE);
        } else {
            // Si todo salió bien, agregamos al árbol
            nuevoFile.setName(nombre.trim());
            dirPadre.addFile(nuevoFile);
            refrescarArbolUI((Directory) ((DefaultMutableTreeNode)arbolDirectorios.getModel().getRoot()).getUserObject());
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error crítico: " + e.getMessage());
    }

    }//GEN-LAST:event_crearActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        if (mode=="admin"){
            //eliminar archivo o directorio
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar1ActionPerformed
        if (mode=="admin"||mode=="user"){
            //lectura de archivo
        }
    }//GEN-LAST:event_eliminar1ActionPerformed

    private void crear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear1ActionPerformed
    if (!jadminisrtador1.isSelected()) {
        JOptionPane.showMessageDialog(this, 
            "Acceso Denegado: Solo el Administrador puede crear directorios.", 
            "Error de Permisos", 
            JOptionPane.ERROR_MESSAGE);
        return; 
    }

    // 2. Obtener el nodo seleccionado en el árbol
    DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) arbolDirectorios.getLastSelectedPathComponent();

    // 3. Validar selección
    if (nodoSeleccionado == null) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione una carpeta en el árbol donde desea crear el directorio.");
        return;
    }

    Object objetoNodo = nodoSeleccionado.getUserObject();
    if (!(objetoNodo instanceof Directory)) {
        JOptionPane.showMessageDialog(this, "No puede crear directorios dentro de un archivo.");
        return;
    }

    Directory carpetaPadre = (Directory) objetoNodo;

    // 4. Pedir el nombre del nuevo directorio
    String nombre = JOptionPane.showInputDialog(this, "Nombre del nuevo directorio:");

    if (nombre != null && !nombre.trim().isEmpty()) {
        // 5. Crear e integrar en la estructura lógica
        Directory nuevaCarpeta = new Directory(nombre);
        carpetaPadre.addDirectory(nuevaCarpeta);

        // 6. Refrescar el JTree visualmente
        // Obtenemos la raíz actual para no perder la estructura completa
        DefaultTreeModel modelo = (DefaultTreeModel) arbolDirectorios.getModel();
        DefaultMutableTreeNode raizNodo = (DefaultMutableTreeNode) modelo.getRoot();
        refrescarArbolUI((Directory) raizNodo.getUserObject());
        
        JOptionPane.showMessageDialog(this, "Directorio '" + nombre + "' creado exitosamente.");
    }
    }//GEN-LAST:event_crear1ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
    if (!jadminisrtador1.isSelected()) {
        JOptionPane.showMessageDialog(this, 
            "Acceso Denegado: Solo el Administrador puede modificar directorios/archivos.", 
            "Error de Permisos", 
            JOptionPane.ERROR_MESSAGE);
        return; 
    }    
        DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) arbolDirectorios.getLastSelectedPathComponent();

    if (nodoSeleccionado == null) {
        JOptionPane.showMessageDialog(this, "Seleccione un archivo o carpeta para renombrar.");
        return;
    }
    Object objeto = nodoSeleccionado.getUserObject();
    String nombreActual = objeto.toString();

    // 3. Pedir el nuevo nombre
    String nuevoNombre = JOptionPane.showInputDialog(this, "Ingrese el nuevo nombre:", nombreActual);

    if (nuevoNombre != null && !nuevoNombre.trim().isEmpty()) {
        // 4. Actualizar la lógica según el tipo de objeto
        if (objeto instanceof File) {
            ((File) objeto).setName(nuevoNombre.trim());
        } else if (objeto instanceof Directory) {
            ((Directory) objeto).setDirectoryName(nuevoNombre.trim());
        }

        // 5. Refrescar visualmente el árbol sin perder la estructura
        DefaultTreeModel modelo = (DefaultTreeModel) arbolDirectorios.getModel();
        modelo.nodeChanged(nodoSeleccionado); 
        
        JOptionPane.showMessageDialog(this, "Nombre actualizado correctamente.");
    }
    }//GEN-LAST:event_updateActionPerformed

    private void JsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JsonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos JSON", "json");
        fileChooser.setFileFilter(filtro);
        int seleccion = fileChooser.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            java.io.File archivo = fileChooser.getSelectedFile();
            try {
                String contenidoJson = new String(Files.readAllBytes(Paths.get(archivo.getAbsolutePath())));
                boolean esValido = validarEstructuraJSON(contenidoJson);
                if (esValido) {
                    JOptionPane.showMessageDialog(this, "Archivo JSON leído y validado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "El archivo JSON no tiene la estructura correcta (faltan campos o hay tipos de datos incorrectos).", "Error de Formato", JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al leer el archivo:\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_JsonActionPerformed

    private void jComboPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboPlanActionPerformed
    if (mode =="admin"){
        //planificador
    }
    }//GEN-LAST:event_jComboPlanActionPerformed

    private void jScrollPane2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jScrollPane2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2ComponentShown

    public void refrescarArbolUI(Directory carpetaRaizLogica) {
        DefaultMutableTreeNode nodoRaizVisual = new DefaultMutableTreeNode(carpetaRaizLogica);
        poblarNodoRecursivo(carpetaRaizLogica, nodoRaizVisual);
        DefaultTreeModel modelo = new DefaultTreeModel(nodoRaizVisual);
        arbolDirectorios.setModel(modelo);
    }

// ==========================================
// EL MÉTODO RECURSIVO (CORREGIDO)
// ==========================================
    private void poblarNodoRecursivo(Directory carpetaLogica, DefaultMutableTreeNode nodoPadreVisual) {
        if (carpetaLogica.getDirectories() != null) {
            Directory actualDir = carpetaLogica.getDirectories().getFirstDirectory();
            while (actualDir != null) {
                DefaultMutableTreeNode nodoSubCarpeta = new DefaultMutableTreeNode(actualDir);
                nodoPadreVisual.add(nodoSubCarpeta);
                poblarNodoRecursivo(actualDir, nodoSubCarpeta);
                actualDir = actualDir.getNext();
            }
        }
        if (carpetaLogica.getFiles() != null) {
            File actualArchivo = carpetaLogica.getFiles().getFirstFile();
            while (actualArchivo != null) {
                DefaultMutableTreeNode nodoArchivo = new DefaultMutableTreeNode(actualArchivo);
                nodoPadreVisual.add(nodoArchivo);
                actualArchivo = actualArchivo.getNext();
            }
        }
    }

private void iniciarDatosDePrueba() {
    // 1. Obtenemos la cola de libres real del disco
    Queue colaReal = miDisco.getColaLibres(); 
    if (colaReal == null) return;

    // 2. Definimos la raíz y carpetas adicionales
    Directory carpetaRaiz = new Directory("Disco C:");
    Directory carpetaFotos = new Directory("Fotos_Vacaciones");
    Directory carpetaDocumentos = new Directory("Mis_Documentos");
    
    carpetaRaiz.addDirectory(carpetaFotos);
    carpetaRaiz.addDirectory(carpetaDocumentos);

    // --- ARCHIVO 1: informe_final.pdf (8 bloques) ---
    File informe = new File(8, colaReal, "Admin");
    informe.setName("informe_final.pdf");
    carpetaDocumentos.addFile(informe); // Guardado en documentos
    
    Color colorRojo = new Color(255, 51, 51);
    Block b1 = informe.getFirstBlock();
    while (b1 != null) {
        miDisco.getVistaDisco().asignarBloqueVisual(b1.getId(), colorRojo);
        b1 = b1.getNext();
    }

    // --- ARCHIVO 2: foto_en_la_playa.jpg (12 bloques) ---
    File foto = new File(12, colaReal, "Usuario");
    foto.setName("foto_en_la_playa.jpg");
    carpetaFotos.addFile(foto); // Guardado en fotos
    
    Color colorAmarillo = new Color(255, 204, 0); // Color arena/playa
    Block b2 = foto.getFirstBlock();
    while (b2 != null) {
        miDisco.getVistaDisco().asignarBloqueVisual(b2.getId(), colorAmarillo);
        b2 = b2.getNext();
    }

    // --- ARCHIVO 3: sistema.log (4 bloques) ---
    File log = new File(4, colaReal, "System");
    log.setName("sistema.log");
    carpetaRaiz.addFile(log); // Guardado en la raíz
    
    Color colorAzul = new Color(51, 153, 255);
    Block b3 = log.getFirstBlock();
    while (b3 != null) {
        miDisco.getVistaDisco().asignarBloqueVisual(b3.getId(), colorAzul);
        b3 = b3.getNext();
    }

    // 3. Refrescar el árbol visual
    refrescarArbolUI(carpetaRaiz);
}
/**
 * Método auxiliar para no repetir el código del 'while' 
 * cada vez que creamos un archivo de prueba.
 */
private void pintarArchivoEnPanel(File archivo, Color color) {
    if (archivo == null) return;
    
    Block aux = archivo.getFirstBlock();
    while (aux != null) {
        // Marcamos el bloque en la vista visual del PanelSD
        miDisco.getVistaDisco().asignarBloqueVisual(aux.getId(), color);
        aux = aux.getNext();
    }
}

     public static void main(String args[]) {

        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.

         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 

         */

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    break;

                }

            }

        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {

            logger.log(java.util.logging.Level.SEVERE, null, ex);

        }

        //</editor-fold>


        /* Create and display the form */

        java.awt.EventQueue.invokeLater(() -> new JFramePrincipal().setVisible(true));

    } 
// ==========================================
    // MÉTODO PARA VALIDAR LA ESTRUCTURA DEL JSON
    // ==========================================
    public boolean validarEstructuraJSON(String contenidoJson) {
    try {
        JSONObject raiz = new JSONObject(contenidoJson);
        
        // 1. LIMPIEZA TOTAL ANTES DE CARGAR
        // Suponiendo que miDisco tiene un método para resetear bloques
        miDisco.reiniciarEstructura(); 
        generalRequests = new Queue("Requests"); // Vaciar cola de peticiones anteriores
        
        // 2. Nueva raíz desde el JSON
        Directory directory = new Directory(raiz.getString("test_id")); 
        
        // 3. Configurar cabezal
        int cabezalInicial = raiz.getInt("initial_head");
        miDisco.getPlanificador().setPosicionCabezal(cabezalInicial);
        
        // 4. Cargar archivos del sistema
        JSONObject systemFiles = raiz.getJSONObject("system_files");
        Iterator<String> keys = systemFiles.keys();
        
        while (keys.hasNext()) {
            String key = keys.next();
            JSONObject fileData = systemFiles.getJSONObject(key);
            
            // miDisco.crearArchivo ya debería manejar la asignación de bloques libres
            File tempFile = miDisco.crearArchivo(fileData.getInt("blocks"), "Admin", obtenerColorAleatorio());
            
            if (tempFile != null) {
                tempFile.setName(fileData.getString("name"));
                directory.addFile(tempFile);
                // Pintamos visualmente los bloques que acaba de ocupar
                pintarArchivoEnPanel(tempFile, obtenerColorAleatorio());
            }
        }          

        // 5. Cargar peticiones (Requests)
        JSONArray requests = raiz.getJSONArray("requests");
        for (int i = 0; i < requests.length(); i++) {
            JSONObject request = requests.getJSONObject(i);
            Request request1 = new Request(request.getInt("pos"), request.getString("op"));
            generalRequests.addRequest(request1);
        }

        // 6. Actualizar la interfaz con la NUEVA estructura
        refrescarArbolUI(directory);
        
        return true;
    } catch (JSONException e) {
        System.out.println("Error de validación: " + e.getMessage());
        return false;
    }
}
    
    private DefaultMutableTreeNode getSelectedNode() {
    return (DefaultMutableTreeNode) arbolDirectorios.getLastSelectedPathComponent();
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Json;
    private javax.swing.JPanel PanelControles;
    private javax.swing.JTree arbolDirectorios;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton crear;
    private javax.swing.JButton crear1;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton eliminar1;
    private javax.swing.JComboBox<String> jComboPlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JRadioButton jadminisrtador1;
    private javax.swing.JRadioButton jusuario;
    private javax.swing.JPanel paneArbol;
    private javax.swing.JPanel panelContenedorDisco;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}