/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sisoperativos2costatucci.gui;

import com.mycompany.sisoperativos2costatucci.logic.Block;
import com.mycompany.sisoperativos2costatucci.logic.Directory;
import com.mycompany.sisoperativos2costatucci.logic.File;
import com.mycompany.sisoperativos2costatucci.logic.GestorDisco;
import com.mycompany.sisoperativos2costatucci.logic.Queue;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import java.awt.Color;

/**
 *
 * @author gabri
 */
public class JFramePrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFramePrincipal.class.getName());
    private GestorDisco miDisco;

    /**
     * Creates new form JFramePrincipal
     */
    public JFramePrincipal() {
        initComponents(); // ¡Esta línea la pone NetBeans, NO la borres ni la muevas!

        // 1. PRIMERO Creamos el disco y su vista visual (181 bloques)
        miDisco = new GestorDisco(181, 50);

        // 2. Extraemos el panel dibujado y lo metemos en el contenedor del NetBeans
        panelContenedorDisco.setLayout(new java.awt.BorderLayout()); // Aseguramos el layout
        panelContenedorDisco.removeAll(); // Limpiamos por si acaso
        panelContenedorDisco.add(miDisco.getVistaDisco(), java.awt.BorderLayout.CENTER);
        panelContenedorDisco.revalidate();
        panelContenedorDisco.repaint();

        // 3. SEGUNDO (Ahora que la pantalla ya tiene la cuadrícula), lanzamos la prueba
        iniciarDatosDePrueba();
    }

// ==========================================
// 1. GENERADOR DE COLORES ALEATORIOS
// ==========================================
    private Color obtenerColorAleatorio() {
        // Generamos valores RGB al azar
        float r = (float) Math.random();
        float g = (float) Math.random();
        float b = (float) Math.random();

        // El .brighter() ayuda a que los colores sean más vivos y no oscurezcan el número negro
        return new Color(r, g, b).brighter();
    }

// ==========================================
// 2. MÉTODO RECURSIVO PARA PINTAR EL DISCO
// ==========================================
    private void pintarArchivosEnDisco(Directory carpetaLogica, PanelSD panelDisco) {

        // A. Recorrer y pintar los ARCHIVOS de esta carpeta
        if (carpetaLogica.getFiles() != null) {
            File actualArchivo = carpetaLogica.getFiles().getFirstFile();

            while (actualArchivo != null) {
                // Creamos un color único para ESTE archivo
                Color colorArchivo = obtenerColorAleatorio();

                // Recorremos la cadena de BLOQUES de este archivo
                Block actualBloque = actualArchivo.getFirstBlock();
                while (actualBloque != null) {
                    // Le decimos a tu PanelSD que pinte este cuadrito específico
                    panelDisco.asignarBloqueVisual(actualBloque.getId(), colorArchivo);

                    actualBloque = actualBloque.getNext(); // Pasamos al siguiente bloque
                }

                actualArchivo = actualArchivo.getNext(); // Pasamos al siguiente archivo
            }
        }

        // B. Recorrer las SUBCARPETAS (Magia recursiva)
        if (carpetaLogica.getDirectories() != null) {
            Directory actualDir = carpetaLogica.getDirectories().getFirstDirectory();

            while (actualDir != null) {
                // Entramos a la subcarpeta a ver qué archivos tiene para pintarlos
                pintarArchivosEnDisco(actualDir, panelDisco);

                actualDir = actualDir.getNext(); // Pasamos a la siguiente subcarpeta
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        PanelControles = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jusuario = new javax.swing.JRadioButton();
        jadminisrtador1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboPlan = new javax.swing.JComboBox<>();
        crear = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        eliminar1 = new javax.swing.JButton();
        crear1 = new javax.swing.JButton();
        update = new javax.swing.JButton();
        Json = new javax.swing.JButton();
        paneArbol = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbolDirectorios = new javax.swing.JTree();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        panelContenedorDisco = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setToolTipText("");

        PanelControles.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setText("Controles");
        jLabel1.setOpaque(true);

        buttonGroup1.add(jusuario);
        jusuario.setText("Usuario");
        jusuario.addActionListener(this::jusuarioActionPerformed);

        buttonGroup1.add(jadminisrtador1);
        jadminisrtador1.setText("Administrador");
        jadminisrtador1.addActionListener(this::jadminisrtador1ActionPerformed);

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Modo:");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Planificador:");
        jLabel3.setOpaque(true);

        jComboPlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIFO", "SSTF", "SCAN", "C-SCAN" }));

        crear.setText("Crear Archivo");
        crear.addActionListener(this::crearActionPerformed);

        eliminar.setText("Eliminar");
        eliminar.addActionListener(this::eliminarActionPerformed);

        eliminar1.setText("Leer");
        eliminar1.addActionListener(this::eliminar1ActionPerformed);

        crear1.setText("Crear Directorio");
        crear1.addActionListener(this::crear1ActionPerformed);

        update.setText("Update");
        update.addActionListener(this::updateActionPerformed);

        Json.setText("Cargar JSON");
        Json.addActionListener(this::JsonActionPerformed);

        javax.swing.GroupLayout PanelControlesLayout = new javax.swing.GroupLayout(PanelControles);
        PanelControles.setLayout(PanelControlesLayout);
        PanelControlesLayout.setHorizontalGroup(
            PanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlesLayout.createSequentialGroup()
                .addGroup(PanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelControlesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(PanelControlesLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(PanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jusuario)
                            .addGroup(PanelControlesLayout.createSequentialGroup()
                                .addGroup(PanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jadminisrtador1))
                                .addGap(63, 63, 63)
                                .addGroup(PanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(PanelControlesLayout.createSequentialGroup()
                                        .addComponent(jComboPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(crear)
                                        .addGap(15, 15, 15)
                                        .addComponent(crear1)
                                        .addGap(18, 18, 18)
                                        .addComponent(eliminar)
                                        .addGap(18, 18, 18)
                                        .addComponent(eliminar1)
                                        .addGap(18, 18, 18)
                                        .addComponent(update)
                                        .addGap(18, 18, 18)
                                        .addComponent(Json)))))))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        PanelControlesLayout.setVerticalGroup(
            PanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jadminisrtador1)
                    .addComponent(jComboPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crear)
                    .addComponent(eliminar)
                    .addComponent(eliminar1)
                    .addComponent(crear1)
                    .addComponent(update)
                    .addComponent(Json))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jusuario)
                .addGap(42, 42, 42))
        );

        paneArbol.setBackground(new java.awt.Color(51, 102, 255));

        jScrollPane1.setViewportView(arbolDirectorios);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sistema de Archivos");
        jLabel4.setOpaque(true);

        javax.swing.GroupLayout paneArbolLayout = new javax.swing.GroupLayout(paneArbol);
        paneArbol.setLayout(paneArbolLayout);
        paneArbolLayout.setHorizontalGroup(
            paneArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneArbolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(paneArbolLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 321, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paneArbolLayout.setVerticalGroup(
            paneArbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneArbolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Log");
        jLabel5.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.setBackground(new java.awt.Color(255, 51, 102));

        panelContenedorDisco.setLayout(new java.awt.BorderLayout());
        jTabbedPane2.addTab("tab1", panelContenedorDisco);

        jTabbedPane1.setOpaque(true);
        jTabbedPane2.addTab("tab2", jTabbedPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelControles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(paneArbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2)
                .addGap(18, 18, 18))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PanelControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jusuarioActionPerformed

    private void jadminisrtador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadminisrtador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jadminisrtador1ActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarActionPerformed

    private void eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar1ActionPerformed

    private void crear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crear1ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void JsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JsonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JsonActionPerformed

    // Método para actualizar la interfaz
    // ==========================================
// MÉTODO PRINCIPAL PARA REFRESCAR EL ÁRBOL
// ==========================================
    public void refrescarArbolUI(Directory carpetaRaizLogica) {
        // 1. Guardamos el OBJETO DIRECTORY completo (no solo el nombre) en el nodo principal
        DefaultMutableTreeNode nodoRaizVisual = new DefaultMutableTreeNode(carpetaRaizLogica);

        // 2. Llenamos ese nodo con tus carpetas y archivos (usando el método recursivo)
        poblarNodoRecursivo(carpetaRaizLogica, nodoRaizVisual);

        // 3. LA MAGIA: Creamos un modelo con tus datos y se lo aplicamos al JTree de NetBeans
        DefaultTreeModel modelo = new DefaultTreeModel(nodoRaizVisual);

        // Aquí usamos la variable que renombraste en NetBeans
        arbolDirectorios.setModel(modelo);
    }

// ==========================================
// EL MÉTODO RECURSIVO (CORREGIDO)
// ==========================================
    private void poblarNodoRecursivo(Directory carpetaLogica, DefaultMutableTreeNode nodoPadreVisual) {

        // 1. Llenar los Subdirectorios
        if (carpetaLogica.getDirectories() != null) {
            // Usamos getFirstDirectory() que es el método real de tu clase Queue
            Directory actualDir = carpetaLogica.getDirectories().getFirstDirectory();

            while (actualDir != null) {
                DefaultMutableTreeNode nodoSubCarpeta = new DefaultMutableTreeNode(actualDir);
                nodoPadreVisual.add(nodoSubCarpeta);

                // Magia recursiva por si esta carpeta tiene más carpetas adentro
                poblarNodoRecursivo(actualDir, nodoSubCarpeta);

                // CORRECCIÓN: Saltamos al siguiente directorio (tu código decía "actualDir.get")
                actualDir = actualDir.getNext();
            }
        }

        // 2. Llenar los Archivos
        if (carpetaLogica.getFiles() != null) {
            // CORRECCIÓN: Usamos getFirstFile() en vez de getHead()
            File actualArchivo = carpetaLogica.getFiles().getFirstFile();

            while (actualArchivo != null) {
                DefaultMutableTreeNode nodoArchivo = new DefaultMutableTreeNode(actualArchivo);
                nodoPadreVisual.add(nodoArchivo);

                // Pasamos al siguiente File en la cola
                actualArchivo = actualArchivo.getNext();
            }
        }
    }

    private void iniciarDatosDePrueba() {
        System.out.println("Iniciando datos de prueba...");

        // ==========================================
        // 1. PREPARAMOS EL DISCO (BITMAP)
        // ==========================================
        // Simulamos un BitMap con 181 bloques libres (para que coincida con tu miDisco)
        Queue bitMapSimulado = new Queue("BitMap Libre");
        for (int i = 0; i < 181; i++) {
            bitMapSimulado.addBlock(new Block(i));
        }

        // ==========================================
        // 2. CREAMOS LA ESTRUCTURA DE CARPETAS
        // ==========================================
        Directory carpetaRaiz = new Directory("Disco C:");
        Directory carpetaDocs = new Directory("Documentos");
        Directory carpetaFotos = new Directory("Imágenes");

        carpetaRaiz.addDirectory(carpetaDocs);
        carpetaRaiz.addDirectory(carpetaFotos);

        // ==========================================
        // 3. CREAMOS LOS ARCHIVOS Y REPARTIMOS BLOQUES
        // ==========================================
        File archivo1 = new File(5, bitMapSimulado, "Admin");
        archivo1.setName("informe_final.pdf");
        carpetaDocs.addFile(archivo1);

        File archivo2 = new File(2, bitMapSimulado, "Admin");
        archivo2.setName("presupuesto.xlsx");
        carpetaDocs.addFile(archivo2);

        File archivo3 = new File(8, bitMapSimulado, "Admin");
        archivo3.setName("foto_playa.png");
        carpetaFotos.addFile(archivo3);

        File archivo4 = new File(3, bitMapSimulado, "Admin");
        archivo4.setName("leame.txt");
        carpetaRaiz.addFile(archivo4);

        // ==========================================
        // 4. ¡DIBUJAMOS EN PANTALLA!
        // ==========================================
        // A. Refrescamos el árbol visual a la izquierda
        refrescarArbolUI(carpetaRaiz);

        // B. ¡CORRECCIÓN AQUÍ! Pintamos usando el panel extraído de tu GestorDisco
        // Hacemos un "cast" a (PanelSD) para asegurarnos de que Java sepa qué tipo de panel es
        pintarArchivosEnDisco(carpetaRaiz, (PanelSD) miDisco.getVistaDisco());

        System.out.println("¡Árbol y Disco dibujados con éxito!");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFramePrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Json;
    private javax.swing.JPanel PanelControles;
    private javax.swing.JTree arbolDirectorios;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton crear;
    private javax.swing.JButton crear1;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton eliminar1;
    private javax.swing.JComboBox<String> jComboPlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JRadioButton jadminisrtador1;
    private javax.swing.JRadioButton jusuario;
    private javax.swing.JPanel paneArbol;
    private javax.swing.JPanel panelContenedorDisco;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
