package com.mycompany.sisoperativos2costatucci.gui;

import javax.swing.*;
import java.awt.*;


public class PanelSD extends JPanel {
    
    // Arreglo básico para guardar las referencias a los cuadritos de la interfaz
    private JPanel[] bloquesVisuales;

    public PanelSD(int totalBloques) {
        // 1. Configuramos el Layout como una cuadrícula (Grid)
        // Calculamos la raíz cuadrada para hacer una cuadrícula perfecta (ej: 100 bloques = 10x10)
        int filasColumnas = (int) Math.ceil(Math.sqrt(totalBloques));
        setLayout(new GridLayout(filasColumnas, filasColumnas, 2, 2)); // 2px de separación entre cuadros
        
        // Un fondo oscuro hará que la separación de 2px parezca una cuadrícula
        setBackground(Color.DARK_GRAY); 
        
        // 2. Inicializamos el arreglo con la cantidad de bloques solicitada
        bloquesVisuales = new JPanel[totalBloques];
        
        // 3. Creamos cada cuadrito, lo pintamos de blanco y lo agregamos al panel
        for (int i = 0; i < totalBloques; i++) {
            JPanel cuadrito = new JPanel();
            cuadrito.setBackground(Color.WHITE); // Blanco = Bloque Libre/Vacío
            
            // Le ponemos un pequeño borde y el número (ID) para que se vea más profesional
            cuadrito.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
            cuadrito.add(new JLabel(String.valueOf(i))); 
            
            // Lo guardamos en el arreglo para poder cambiarle el color después
            bloquesVisuales[i] = cuadrito; 
            
            // Lo añadimos a la cuadrícula del PanelSD
            add(cuadrito); 
        }
    }

    // --- MÉTODOS PÚBLICOS QUE USA EL GESTORDISCO ---

    // Cambia el color del bloque cuando se asigna a un archivo
    public void asignarBloqueVisual(int id, Color color) {
        // Validamos que el ID exista dentro del disco para evitar errores
        if (id >= 0 && id < bloquesVisuales.length) {
            bloquesVisuales[id].setBackground(color);
        }
    }

    // Devuelve el bloque al color blanco cuando se elimina un archivo
    public void liberarBloqueVisual(int id) {
        if (id >= 0 && id < bloquesVisuales.length) {
            bloquesVisuales[id].setBackground(Color.WHITE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
